export const industries = [
	{ id: 'ARD', label: 'Aerospace and Defense' },
	{ id: 'AGF', label: 'Agriculture and Forestry' },
	{ id: 'ARC', label: 'Arts and Crafts' },
	{ id: 'AUT', label: 'Automotive' },
	{ id: 'BFS', label: 'Banking and Financial Services' },
	{ id: 'BIO', label: 'Biotechnology' },
	{ id: 'CHM', label: 'Chemicals' },
	{ id: 'CLT', label: 'Clean Technology' },
	{ id: 'CNE', label: 'Construction and Engineering' },
	{ id: 'CNM', label: 'Construction Materials' },
	{ id: 'CGD', label: 'Consumer Goods' },
	{ id: 'EDT', label: 'Education and Training' },
	{ id: 'ELS', label: 'Electronics and Semiconductors' },
	{ id: 'ENR', label: 'Energy (Oil, Gas, Renewable)' },
	{ id: 'ENT', label: 'Entertainment and Media' },
	{ id: 'FAP', label: 'Fashion and Apparel' },
	{ id: 'FDB', label: 'Food and Beverage' },
	{ id: 'GPS', label: 'Government and Public Services' },
	{ id: 'HCP', label: 'Healthcare and Pharmaceuticals' },
	{ id: 'HOT', label: 'Hospitality and Tourism' },
	{ id: 'HRS', label: 'Human Resources and Staffing' },
	{ id: 'ITS', label: 'Information Technology and Software' },
	{ id: 'INS', label: 'Insurance' },
	{ id: 'LOG', label: 'Logistics and Transportation' },
	{ id: 'MNF', label: 'Manufacturing' },
	{ id: 'MAD', label: 'Marketing and Advertising' },
	{ id: 'MAP', label: 'Media and Publishing' },
	{ id: 'MNM', label: 'Mining and Metals' },
	{ id: 'NCO', label: 'Nonprofit and Charitable Organizations' },
	{ id: 'PSB', label: 'Personal Services (Beauty, Wellness)' },
	{ id: 'PNP', label: 'Printing and Publishing' },
	{ id: 'PRS', label: 'Professional Services (Consulting, Legal, Accounting)' },
	{ id: 'RPM', label: 'Real Estate and Property Management' },
	{ id: 'RTC', label: 'Retail and E-commerce' },
	{ id: 'SAS', label: 'Security and Surveillance' },
	{ id: 'SAR', label: 'Sports and Recreation' },
	{ id: 'TEL', label: 'Telecommunications' },
	{ id: 'TXT', label: 'Textiles' },
	{ id: 'UTL', label: 'Utilities (Water, Electricity, Waste Management)' },
	{ id: 'VCP', label: 'Venture Capital and Private Equity' }
];

export const investorType = [
	{ id: 'IND', label: 'Individual Investor' },
	{ id: 'INS', label: 'Institutional Investor' }
];
