import {
	Building,
	Building2,
	Facebook,
	Instagram,
	Linkedin,
	Mail,
	Youtube,
	CircleCheckBig,
	IdCard,
	Smartphone,
	MapPin,
	Clock,
	Info,
	Banknote,
	CircleChevronRight,
	CircleChevronLeft,
	CircleChevronDown,
	CircleChevronUp,
	CircleDot,
	ChevronRight,
	ChevronLeft,
	ChevronDown,
	ChevronUp,
	LogIn,
	UserRound,
	FileStack,
	ListTodo,
	HandCoins,
	MoveRight,
	Send,
	MessagesSquare,
	CircleX
} from 'lucide-svelte';
import Koredor from './koredor.svelte';
import IconButton from './icon-button.svelte';
import Koredorwhite from './koredorwhite.svelte';

export const Icons = {
	facebook: Facebook,
	instagram: Instagram,
	linkedin: Linkedin,
	youtube: Youtube,
	koredor: Koredor,
	koredorwhite: Koredorwhite,
	iconButton: IconButton,
	circleCheckBig: CircleCheckBig,
	idCard: IdCard,
	building: Building,
	building2: Building2,
	email: Mail,
	smartphone: Smartphone,
	mapPin: MapPin,
	clock: Clock,
	info: Info,
	banknote: Banknote,
	circleChevronRight: CircleChevronRight,
	circleChevronLeft: CircleChevronLeft,
	circleChevronDown: CircleChevronDown,
	circleChevronUp: CircleChevronUp,
	circleDot: CircleDot,
	logIn: LogIn,
	userRound: UserRound,
	chevronRight: ChevronRight,
	chevronLeft: ChevronLeft,
	chevronDown: ChevronDown,
	chevronUp: ChevronUp,
	fileStack: FileStack,
	listTodo: ListTodo,
	handCoins: HandCoins,
	send: Send,
	moveRight: MoveRight,
	messagesSquare: MessagesSquare,
	circleX: CircleX
};
