import {
	Facebook,
	Instagram,
	Linkedin,
	Mail,
	Youtube,
	CircleCheckBig,
	IdCard,
	Building,
	Smartphone,
	MapPin,
	Clock,
	Info,
	Banknote,
	CircleChevronRight,
	CircleChevronLeft,
	CircleChevronDown,
	CircleChevronUp,
	CircleDot,
} from 'lucide-svelte';
import Koredor from './koredor.svelte';
import IconButton from './icon-button.svelte';

export const Icons = {
	facebook: Facebook,
	instagram: Instagram,
	linkedin: Linkedin,
	youtube: Youtube,
	koredor: Koredor,
	iconButton: IconButton,
	circleCheckBig: CircleCheckBig,
	idCard: IdCard,
	building: Building,
	email: Mail,
	smartphone: Smartphone,
	mapPin: MapPin,
	clock: Clock,
	info: Info,
	banknote: Banknote,
	circleChevronRight: CircleChevronRight,
	circleChevronLeft: CircleChevronLeft,
	circleChevronDown: CircleChevronDown,
	circleChevronUp: CircleChevronUp,
	circleDot: CircleDot,
};
